# See https://cloud.google.com/appengine/docs/standard/php/config/appref for a
# complete list of `app.yaml` directives.

runtime: php81

env_variables:
    GOOGLE_STORAGE_BUCKET: "capstone-bs-bvc"
    # populate these to use the "mysql" or "postres" backends
    CLOUDSQL_CONNECTION_NAME: "test-project-379806:us-west1:poste"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "bvccapstone"
    ## Uncomment to give your database a name other than "bookshelf"
    CLOUDSQL_DATABASE_NAME: "poste"
