# See https://cloud.google.com/appengine/docs/standard/php/config/appref for a
# complete list of `app.yaml` directives.

runtime: php81

env_variables:
    GOOGLE_STORAGE_BUCKET: "capstone-bs-bvc"
    # populate these to use the "mysql" or "postres" backends
    CLOUDSQL_CONNECTION_NAME: "poste-388319:us-east1-b:poste"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "9FgIZrcgTnUIZ3PWsAMmg13fyLEnRsEHjdy68nV6MQOwcfE1oDLkDC64YjwIhXsv9NNhC53f6wAOnYRFrQTL7UMxawSNIt2Iu15V"
    ## Uncomment to give your database a name other than "bookshelf"
    CLOUDSQL_DATABASE_NAME: "poste"
