# See https://cloud.google.com/appengine/docs/standard/php/config/appref for a
# complete list of `app.yaml` directives.

runtime: php81

env_variables:
    GOOGLE_STORAGE_BUCKET: "poste-picture-storage"
    CLOUDSQL_CONNECTION_NAME: "poste-388415:us-central1:poste"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "mtQ7XfjJqjVIxeUqFVYSIom4d6lmCV"
    CLOUDSQL_DATABASE_NAME: "poste-data"
