name: Android CI

on:
  push:
    branches: [ "dev",  "main"]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Replace Certificate
      run: |
        echo "${{ secrets.REAL_CERTIFICATE }}" | base64 -d > .app/src/main/res/raw/poste.crt

    - name: Build with Gradle
      run: ./gradlew assembleDevelopment
