name: Android CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:
    branches:
      - "master"
      - "feature/**"

jobs:
  build:

    # env:
    #   ANDROID_HOME: C:\Users\Administrator\AppData\Local\Android\Sdk

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Download Android SDK
      run: |
        Invoke-WebRequest -Uri https://dl.google.com/android/repository/commandlinetools-win-7302050_latest.zip -OutFile android-sdk.zip
        Expand-Archive -Path android-sdk.zip -DestinationPath android-sdk

    - name: Accept Android licenses
      run: |
        Set-Location -Path android-sdk/cmdline-tools/bin
        .\sdkmanager.bat --licenses
        Set-Location -Path ../../../..

    - name: Set up environment variables
      run: |
        echo "export ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PWD/android-sdk/cmdline-tools/bin;$PATH" >> $GITHUB_ENV

    - name: Manually add javax.xml.bind module
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?><modules><module name="java.xml.bind"/></modules>' > android-sdk/cmdline-tools/lib/jdeps/jdk.jdeps

    - name: Build with Gradle
      run: ./gradlew build --stacktrace
