name: Android CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:
    branches:
      - "master"
      - "feature/**"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Create local.properties
      run: |
        dir
        echo C\:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk > local.properties

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
  
    # - name: Build all artifacts
    #   id: buildAllApks
    #   uses: eskatos/gradle-command-action@v1.3.3
    #   with:
    #     gradle-version: current
    #     wrapper-cache-enabled: true
    #     dependencies-cache-enabled: true
    #     configuration-cache-enabled: true
    #     arguments: assembleRelease

    - name: Build with Gradle
      run: ./gradlew build
