name: Android CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:
    branches:
      - "master"
      - "feature/**"

jobs:
  build:

    env:
      ANDROID_HOME: C:\Users\Administrator\AppData\Local\Android\Sdk

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create local.properties
      run: |
        echo %ANDROID_HOME%
        echo sdk.dir=C\:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk > local.properties

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
  
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Refresh Dependencies
      run: Z:\actions-runner\_workPoste\Poste\Poste\gradlew --refresh-dependencies --stacktrace

    - name: Build with Gradle
      run: Z:\actions-runner\_workPoste\Poste\Poste\gradlew build --stacktrace
