name: Android CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:
    branches:
      - "master"
      - "feature/**"

jobs:
  build:

    # env:
    #   ANDROID_HOME: C:\Users\Administrator\AppData\Local\Android\Sdk

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Create local.properties
    #   run: |
    #     echo %ANDROID_HOME%
    #     echo sdk.dir=C\:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk > local.properties

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create required-modules directory
      run: New-Item -ItemType Directory -Path "$Env:JAVA_HOME/lib/mods" -Force

    - name: Install missing Java modules
      run: |
        echo "javax.xml.bind" >> "$Env:JAVA_HOME/lib/mods/required-modules"

    - name: Download Android SDK
      run: |
        Invoke-WebRequest -Uri https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip -OutFile android-sdk.zip
        Expand-Archive -Path android-sdk.zip -DestinationPath android-sdk

    - name: Accept Android licenses
      run: |
        Set-Location -Path android-sdk\tools\bin
        .\sdkmanager.bat --licenses
        Set-Location -Path ../../..

    - name: Set up environment variables
      run: |
        echo "export ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PWD/android-sdk/platform-tools;$PWD/android-sdk/tools;$PATH" >> $GITHUB_ENV

    # - name: Setup Gradle
    #   uses: gradle/gradle-build-action@v2

    # - name: Refresh Dependencies
    #   run: ./gradlew --refresh-dependencies --stacktrace

    - name: Build with Gradle
      run: ./gradlew build --stacktrace
